#!/usr/bin/env python3
"""Summarise the fixed MCNP geometry coverage corpus for the manuscript.

The input manifest is deliberately geometry-deduplicated.  This script keeps
the paper's coverage claims reproducible by deriving every count from that
manifest instead of hand-copying numbers into a table.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path


FEATURES = (
    ("union", "Union operator (:)", "occurrences"),
    ("cell_complement", "Cell complement (#cell)", "occurrences"),
    ("group_complement", "Grouped complement", "occurrences"),
    ("universe", "Universe assignment (U)", "occurrences"),
    ("fill", "Universe fill (FILL)", "occurrences"),
    ("lattice", "Lattice declaration (LAT)", "occurrences"),
    ("trcl", "Cell transform (TRCL)", "occurrences"),
    ("transform", "Surface/data transform (TR/*TR)", "occurrences"),
    ("like_but", "LIKE/BUT cell", "occurrences"),
)


def build_summary(manifest: dict) -> dict:
    cases = manifest["coverage"]
    surface_histogram: Counter[str] = Counter()
    feature_rows = []
    for key, label, unit in FEATURES:
        occurrences = sum(int(case.get(key, 0)) for case in cases)
        feature_rows.append(
            {
                "key": key,
                "label": label,
                "cases_present": sum(bool(case.get(key, 0)) for case in cases),
                "occurrences": occurrences,
                "unit": unit,
            }
        )
    for case in cases:
        surface_histogram.update(case.get("surface_histogram", {}))

    warnings = Counter()
    for case in cases:
        warnings.update(case.get("baseline_warning_categories", {}))

    return {
        "manifest_schema_version": manifest.get("schema_version"),
        "selection_rule": manifest.get("selection_rule", {}),
        "cases": len(cases),
        "cells": sum(int(case["cells"]) for case in cases),
        "surfaces": sum(int(case["surfaces"]) for case in cases),
        "unique_surface_types": len(surface_histogram),
        "surface_histogram": dict(sorted(surface_histogram.items())),
        "features": feature_rows,
        "baseline": {
            "converted": sum(bool(case.get("baseline_converted")) for case in cases),
            "xml_well_formed": sum(bool(case.get("baseline_xml_well_formed")) for case in cases),
            "gdml_integrity_valid": sum(
                bool(case.get("baseline_gdml_integrity_valid")) for case in cases
            ),
            # A case is clean only when the baseline recorded no warning at
            # all.  Restricting this to the ``geometry`` category would hide
            # explicitly reported approximation warnings classified elsewhere.
            "warning_free": sum(int(case.get("baseline_warning_count", 0)) == 0 for case in cases),
            "geometry_degradation_free": sum(
                not any(
                    int(case.get("baseline_warning_categories", {}).get(name, 0))
                    for name in ("geometry", "other", "bbox")
                )
                for case in cases
            ),
            "source_material_complete": sum(
                not bool(
                    case.get("baseline_warning_categories", {}).get("source_material_missing", 0)
                )
                for case in cases
            ),
            "warning_categories": dict(sorted(warnings.items())),
        },
    }


def markdown(summary: dict) -> str:
    baseline = summary["baseline"]
    lines = [
        "# Geometry coverage corpus summary",
        "",
        "This file is generated by `tools/summarize_corpus_coverage.py`; do not edit counts manually.",
        "",
        "## Corpus",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Geometry-deduplicated cases | {summary['cases']} |",
        f"| MCNP cells | {summary['cells']:,} |",
        f"| MCNP surfaces | {summary['surfaces']:,} |",
        f"| Surface types observed | {summary['unique_surface_types']} |",
        f"| Converted | {baseline['converted']}/{summary['cases']} |",
        f"| Well-formed GDML XML | {baseline['xml_well_formed']}/{summary['cases']} |",
        f"| Internal GDML references valid | {baseline['gdml_integrity_valid']}/{summary['cases']} |",
        f"| Warning-free conversion | {baseline['warning_free']}/{summary['cases']} |",
        f"| No geometry-degradation warning | {baseline['geometry_degradation_free']}/{summary['cases']} |",
        f"| Source material cards complete | {baseline['source_material_complete']}/{summary['cases']} |",
        "",
        "## Feature presence",
        "",
        "| Feature | Cases containing feature | Occurrences |",
        "|---|---:|---:|",
    ]
    lines.extend(
        f"| {row['label']} | {row['cases_present']} | {row['occurrences']:,} |"
        for row in summary["features"]
    )
    lines.extend(["", "## Surface-type histogram", "", "| Surface type | Occurrences |", "|---|---:|"])
    lines.extend(
        f"| `{stype}` | {count:,} |"
        for stype, count in summary["surface_histogram"].items()
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest", type=Path)
    parser.add_argument("--json-out", type=Path, required=True)
    parser.add_argument("--markdown-out", type=Path, required=True)
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    summary = build_summary(manifest)
    args.json_out.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    args.markdown_out.write_text(markdown(summary), encoding="utf-8")


if __name__ == "__main__":
    main()
